### ISSUE TITLE
[bug?] match 正则表达式后行断言后接捕获组 匹配不符合预期

### ISSUE THREAD

**Issue by fanslar** [Simon-He95/vscode-highlight-text#7]
hello

我的规则
```json
        "default": {
          "match": [
            "(?<=( v-for=\"))[^\"]+(?=\")",
            "(?<=( v-(text|html|show|if|else-if|model)=\"))[^\"]+(?=\")",
            "(?<=( (v-bind)?:[\\w-]*)=\")[^\"]+(?=\")",
          ],
          "border": "2px solid #fff",
        },
```
我的预期
![image](https://github.com/Simon-He95/vscode-highlight-text/assets/50618743/5f717636-3c83-4872-86ac-226856e3675f)

实际表现
![image](https://github.com/Simon-He95/vscode-highlight-text/assets/50618743/2f6b54b0-5b03-4271-a809-2d08eaec8f7c)

插件相关代码
![image](https://github.com/Simon-He95/vscode-highlight-text/assets/50618743/ba8f544a-6dee-4e9a-b8cc-ef0273a69424)

调试结果
![image](https://github.com/Simon-He95/vscode-highlight-text/assets/50618743/9ad908aa-0f06-4bff-99af-ff134492e5dc)

原因应该是后行断言的匹配结果不包含其中捕获组的内容，而插件中matchText又会遍历去拿捕获组的内容，导致matcher[0].indexOf(matchText)始终为-1，而length也为捕获组长度，而不是匹配项长度；结果就会如图中，始终偏左一个单位，选取长度对不上
我目前本地直接修改为
```ts
            // const start = matcher.index! + matcher[0].indexOf(matchText)
            // const end = start + matchText.length
            const start = matcher.index!
            const end = start + matcher[0].length
```
但我不确定作者你有什么考量，我本身代码水平有限，正则苦手，可能有什么简单的方法就可以解决我的问题，希望作者指点一下

**Comment by Simon-He95** [comment]
他是为了处理针对多个匹配项可以设置不通的颜色，你如果希望全部一个颜色的话可以用`?:` 去忽略 match 项
`"(?<=(?: v-for=\"))[^\"]+(?=\")"` , 如果多个匹配的话，可以用 [`colors`](https://github.com/Simon-He95/vscode-highlight-text?tab=readme-ov-file#2-you-can-set-different-styles-for-multiple-match-items-in-a-regular-rule) 去进一步处理后续的颜色控制

**Comment by fanslar** [comment]
我™犯蠢了，这个match数组中任意一个正则中存在match项不仅会影响自己的匹配，也会影响其他的正则，之前调试偷懒，只改了其中一个正则中的`?:` 去忽略 match 项想看看效果，怎么都不好使。尴尬了 : (
