### ISSUE TITLE
用文档配制不生效

### ISSUE THREAD

**Issue by cbychen** [Simon-He95/vscode-highlight-text#8]
<img width="815" alt="image" src="https://github.com/Simon-He95/vscode-highlight-text/assets/102778109/144d54b2-d280-45c7-9253-9035352a1b85">

<img width="838" alt="image" src="https://github.com/Simon-He95/vscode-highlight-text/assets/102778109/2a6c8e72-d0b3-4cfc-9e13-2f8dbb160da7">

按照文档中的配额制直接复制过去 发现vue文件中 v-if 并没有生效  颜色和前置内容都没有，是要开启什么配制吗

**Comment by Simon-He95** [comment]
<img width="328" alt="image" src="https://github.com/Simon-He95/vscode-highlight-text/assets/57086651/bf57c488-a044-47e6-abcb-60061f75f572">
这个是vscode参数定义，代表要传的类型并不是让你直接复制的,参考下面👇
<img width="468" alt="image" src="https://github.com/Simon-He95/vscode-highlight-text/assets/57086651/b2fcb8d6-59f7-44cc-8cf4-b3a456551d59">
