### ISSUE TITLE
如何使得 .txt 文件也能应用配置样式

### ISSUE THREAD

**Issue by Naturalgithub** [Simon-He95/vscode-highlight-text#9]

**Comment by Simon-He95** [comment]
> _No description provided._

他是根据 languageId, 应该对应是 plaintext？ 还是啥来着, 回头可以加一个映射对应 txt，你试试下面图里的
<img width="298" alt="image" src="https://github.com/user-attachments/assets/8c604529-f2a0-4c5d-89d7-e48debe2025c">

**Comment by Simon-He95** [comment]
最新版本支持直接用 txt:{dark:{},light:{}} 配置了
